### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by boostup** [boostup/react-spotify-clone-app#1]
# Bugs

- [ ] virtual keyboard appears when navigating away from search page. It should not.
- [ ] In night mode, Material UI `Menu` component backdrop is hiding the whole app UI, and the menu options are bearly legible
- [x] Logout procedure -> because when logging out, all sagas for home page are triggering needlessly. BW, the automatic auth_error flow does it correctly => DRY
- [x] Must rehydrate user after a full page browser refresh => isPlaylistOwner && isPlaylistFollowedByUser depend on this being correct, and also the user picture not showing in Avatar Area
- [x] A crash was detected when track image is not supplied by API => was resolved by not displaying track that are local to user computer.  By filtering those out, the API guarantees an image for every track.
- [x] CSS bug : cannot scroll all the way down to the list of playlists, nor the list of songs => fixed by revamping the layout, which gave birth to the `MainLayoutPageWrapper` component
- [x] CSS bug on the right of the footer (had to set it to 96% for some unknown reason) -> if I set `box-sizing: border-box;` on the footer, I can set its witdh to 100%, and this fixes the issue
- [x] rehydrate token: when on routes like `/library` or `/home`, basically any route where the component makes an API request will fail if I reload the app using the `reload` button of the browser. This is because, as per the JS error in the console, the API did not receive the bearer token along with the request.

**Comment by boostup** [comment]
CSS I never met before or that I always struggle to remember :
- box-sizing: border-box;
- object-fit: contain;
- place-items: center;
- user-select: none;
- pointer-events: none;
- height: 20vw;
- box-shadow: 0 4px 60px rgba(0, 0, 0, 0.5);

- body::-webkit-scrollbar {
  /* NICE TRICK : it hides the scrollbar, but the scrolling behavior is maintained*/
  display: none;
}

- :root {
  --main-font-color: white;
  --main-theme-color: 0, 0, 0;
  --main-background-color: 4, 4, 4;
  --main-interactive-text-color: #b3b3b3;
}

- @keyframes wheel {
  from {
    transform: rotateZ(0deg);
  }
  to {
    transform: rotateZ(360deg);
  }
}

- /* what is this star meaning here in this particular case ????  */
.footer__right * .MuiSlider-root {
  color: #1ed15e;
}

**Comment by boostup** [comment]
## Quick note

### Bugs

A crash was detected when track image is not supplied by API
 - This means I must handle a placeholder pic and manage whereever this case can happen

### General work

- Rename SongList and SongRow to TrackList and TrackRow
- Rename SquareCover to ItemCover. Not PlaylistCover because it could potientially also be used to display albums or artits (ie the search results which will be filterable by PL, Artist or Album)

**Comment by boostup** [comment]
## SPOTIFY API CLIPBOARD

#### Spotify API scopes
```
const scopes = [
  "user-read-currently-playing",
  "user-read-recently-played",
  "user-read-playback-state",
  "user-top-read",
  "user-modify-playback-state",
];
```

### Me / Personnalisatin
-     getRecommendations(
- getMyRecentlyPlayedTracks(
- getMyTopArtists(
- getMyTopTracks(
- containsMySavedTracks(
      trackIds: string[],
- addToMySavedTracks(
      trackIds: string[],
- removeFromMySavedTracks(
      trackIds: string[],
- getMySavedTracks

### Music info
 getNewReleases(
    getAlbum(
    getAlbumTracks(
    getTrack(
    getTracks(
      trackIds: string[],
    getArtist(
    getArtistAlbums(
    getArtistTopTracks(
    getArtistRelatedArtists(
 getNewReleases(


### Playlist management

### Following
    isFollowingArtists(
    followPlaylist(
    unfollowPlaylist(
unfollowArtists(


###   Devices

getMyDevices(): 

### Playback
    getMyCurrentPlaybackState(
    getMyCurrentPlayingTrack(
    transferMyPlayback(
      deviceIds: string[],

- queue(
- play(options?: SpotifyApi.PlayParameterObject): Promise<void>;
- pause(
- skipToNext(
- skipToPrevious(
- seek(
- setRepeat(
- setVolume( volumePercent: number,
- setShuffle(

```
  // for progress bar:
  // - currentplaybackState?.item.duration_ms
  // - currentplaybackState?.progress_ms

  // currentplaybackState?.repeat_state: track, context, off
  // currentplaybackState?.shuffle_state: true, false
  // currentplaybackState?.item.type: "track"
  // currentplaybackState?.currently_playing_type;
  // currentplaybackState?.timestamp;

  console.log("IS PLAYING", isPlaying);
  console.log("VOLUME PERCENT", volume);
  console.log("MUTE STATE", muteButtonState);
  console.log("SHUFFLE", shuffle);
  console.log("REPEAT", repeat);
  console.log("TRACK NAME", currentTrackName);
  console.log("ALBUM IMAGE", albumImage);
  console.log("ALBUM NAME", albumName);
  console.log("ARTISTS", artists);

    // => condition to reach bottom in case I need it: `element.scrollHeight - element.scrollTop === element.clientHeight`

  
    togglefollowPlaylist,
    isPlaylistFollowedByUser,
  
    // @TODO:
    window.scrollTo(0, 0); => need to do this for the Body component scroll level

  // @TODO:
  const isFollowed = isPlaylistFollowedByUser({
    playlistId: id,
    userId: user.id,
  });

          // @TODO:  toggle AND refactor with playlist toolbar!
          //  @TODO : create new `featured` page
          // @ TODO : new Radio page => using `setMyRecommendedTracks` action

{/* <FavoriteIcon className="playlistToolbar__favorite" fontSize="large" /> */}

  <p>{/* {id} * {playlist?.owner.id} * {user.id} */}</p>
  
  import QueuePlayNextIcon from "@material-ui/icons/QueuePlayNext";
  import ExitToAppIcon from '@material-ui/icons/ExitToApp';
  import ShuffleIcon from "@material-ui/icons/Shuffle";
  import RepeatIcon from "@material-ui/icons/Repeat";
  import FavoriteBorderIcon from "@material-ui/icons/FavoriteBorder";  

```

**Comment by boostup** [comment]
# Quick note taking

- default playlist was Discover Weekly "37i9dQZEVXcDGlrEgKnU30"

- playlist with 100+ tracks : 37i9dQZF1DX32oVqaQE8BM - [Chill Out Music](http://localhost:3000/#/playlist/37i9dQZF1DX32oVqaQE8BM)

- album : http://localhost:3000/#/album/4kwN0SqdqyuOrp7e409uj4

## General work

- virtualized list for
        - [ ] sidebar
        - [ ] ItemPage (=> TrackList component)

- Track `More Icon` : Copy track link to clipboard (React provides Synthetic events for this BTW) 

### Further to the integration of the new SpotifLy backend

#### Token Refresh

- Check if this is all that is need to refresh token, in which case, the whole process of refreshing token upon `invalid access token` response from Spotify API is return, becomes all much simpler !!
    - https://github.com/vercel/next.js/blob/bb1bdbb10fb7f8b4f5d6b05c5e63ba589151cb50/examples/cms-wordpress/lib/api.js#L103

```
  if (process.env.WORDPRESS_AUTH_REFRESH_TOKEN) {
    headers[
      'Authorization'
    ] = `Bearer ${process.env.WORDPRESS_AUTH_REFRESH_TOKEN}`
  }
```

- This backend functionality remains to be tested
- Check the following is still necessary and if so, make sure the code enforces it :
    - When starting auth with stored token: 
        1) rehydrate Token & User data into the redux store in case the browser `page refresh` functionality was triggered by the user
        2) check token expiry prior to every Spotify API call.  The `authWithStoredTokenStart` used to end up setting `authState.success` to false, which would redirect the user the login page.  Now instead, the backen refresh token should be invoked prior any Spotify API call, to ensure this API does not throw an execption of the frontend app.

**Comment by boostup** [comment]
# To research

When an item in the list below is checked, i means the research was done, but has not necessarily been integrated yet into code base.

- [x] route animated transitions ?
- [x] contentEditable (for possible playlist details edition)
- [x] [Firestore offline/online sync](https://youtu.be/ciu62KLlwGQ?t=350)
- [x] Unit Testing
- [x] Migrate to project to NextJS
- [x] check if infinite loading can be refactored using [Vercel's SWR](https://swr.vercel.app/examples/infinite-loading)
- [x] check if scroll detection can be refactored using the [material ui hook](https://material-ui.com/components/app-bar/#scrolling)
- [x] Ellipsis for rows of options in the `Playlists` section of sidebar (color, vertical padding, one-line only, [ellipsis materialUI]
- [x] finish [intermediate ](https://redux-toolkit.js.org/tutorials/intermediate-tutorial#examining-the-original-todos-reducer) and advanced tuts from the redux-toolkit
- [x] inegration of redux-toolkit or setup redux for the redux devtools extension
- [x] Implementing private routes : https://reactrouter.com/web/example/auth-workflow 
- [x] Spotify refresh token flow: https://www.youtube.com/watch?v=n6d4KHSKqGk&feature=youtu.be&t=556
- [x] React-router transition animations: https://reactrouter.com/web/example/animated-transitions
(https://material-ui.com/system/display/) ) | [Typography -> noWrap](https://material-ui.com/api/typography/)
- [x] How to handle the paginated playlist results from API ? Should I get all playlists at once, or should I do a sort of infinite loader ? **the response object has properties `next` and `previous` which is a url I can fetch**
- [x] useReducer + sagas => https://github.com/redux-saga/redux-saga/issues/1692#issuecomment-636096302
- [x] combineReducers => https://codesandbox.io/s/combinereducers-a-la-redux-zdv7f?file=/src/index.js
- [x] must i remove the `:hover` for touch screen on scrolling lists.  It seems they are sporadically getting stuck.
- [x] recoving from `ErrorBoundary` error=true => using a package called `react-error-boundary` that wraps `ErrorBoundary`, which seems much easier to work with


---

**Comment by boostup** [comment]
# Clipboard

## API field selection
```
//fields for playlist
id,name,description,images,owner(display_name),primary_color,type,tracks(limit,next,offset,total,items(track(id,name,album(album_type,artists),is_local,is_playable,popularity,duration_ms,explicit,artists)))

//@TODO fields for albums
```

#### Spotify API scopes
```
const scopes = [
  "user-read-currently-playing",
  "user-read-recently-played",
  "user-read-playback-state",
  "user-top-read",
  "user-modify-playback-state",
];
```

### Me / Personnalisatin
-     getRecommendations(
- getMyRecentlyPlayedTracks(
- getMyTopArtists(
- getMyTopTracks(
- containsMySavedTracks(
      trackIds: string[],
- addToMySavedTracks(
      trackIds: string[],
- removeFromMySavedTracks(
      trackIds: string[],
- getMySavedTracks

### Music info
 getNewReleases(
    getAlbum(
    getAlbumTracks(
    getTrack(
    getTracks(
      trackIds: string[],
    getArtist(
    getArtistAlbums(
    getArtistTopTracks(
    getArtistRelatedArtists(
 getNewReleases(


### Playlist management

### Following
    isFollowingArtists(
    followPlaylist(
    unfollowPlaylist(
unfollowArtists(


###   Devices

getMyDevices(): 

### Playback
    getMyCurrentPlaybackState(
    getMyCurrentPlayingTrack(
    transferMyPlayback(
      deviceIds: string[],

- queue(
- play(options?: SpotifyApi.PlayParameterObject): Promise<void>;
- pause(
- skipToNext(
- skipToPrevious(
- seek(
- setRepeat(
- setVolume( volumePercent: number,
- setShuffle(

```
  // for progress bar:
  // - currentplaybackState?.item.duration_ms
  // - currentplaybackState?.progress_ms

  // currentplaybackState?.repeat_state: track, context, off
  // currentplaybackState?.shuffle_state: true, false
  // currentplaybackState?.item.type: "track"
  // currentplaybackState?.currently_playing_type;
  // currentplaybackState?.timestamp;

  console.log("IS PLAYING", isPlaying);
  console.log("VOLUME PERCENT", volume);
  console.log("MUTE STATE", muteButtonState);
  console.log("SHUFFLE", shuffle);
  console.log("REPEAT", repeat);
  console.log("TRACK NAME", currentTrackName);
  console.log("ALBUM IMAGE", albumImage);
  console.log("ALBUM NAME", albumName);
  console.log("ARTISTS", artists);

    // => condition to reach bottom in case I need it: `element.scrollHeight - element.scrollTop === element.clientHeight`

  
    togglefollowPlaylist,
    isPlaylistFollowedByUser,
  

  const isFollowed = isPlaylistFollowedByUser({
    playlistId: id,
    userId: user.id,
  });



{/* <FavoriteIcon className="playlistToolbar__favorite" fontSize="large" /> */}

  <p>{/* {id} * {playlist?.owner.id} * {user.id} */}</p>
  
  import QueuePlayNextIcon from "@material-ui/icons/QueuePlayNext";
  import ExitToAppIcon from '@material-ui/icons/ExitToApp';
  import ShuffleIcon from "@material-ui/icons/Shuffle";
  import RepeatIcon from "@material-ui/icons/Repeat";
  import FavoriteBorderIcon from "@material-ui/icons/FavoriteBorder";  

```
---

```
  // const userId = user?.id;
  // const isPlaylistOwner = playlist?.owner.id === userId;

      // userId &&
    //   !isPlaylistOwner &&
    //   isPlaylistFollowedByUser({ playlistId: id, userId }, dispatch);


            {/* <p>
            {id} * {playlist?.owner.id} * {userId}
          </p> */}

          //Toolbar

                    // isOwner={isPlaylistOwner}
          // isPlaylistFollower={}
          // toggleFollowPlaylist={}
```

**Comment by boostup** [comment]
## App Technical Characteristics
- [**Micro Frontends / micro services**](https://micro-frontends.org/) : each part of the layout (header, sidebar, body, pages, and footer) are containers that all live independently of each other.  As such, they fetch the data they need and feed it to the children which compose their own branch of the components tree. Provides better separation of concerns, enhances code maintainability, and enables infinite scaling of features.

- [**Flux Architecture**](https://dev.to/boostup/the-flux-architectural-pattern-using-usereducer-the-context-api-and-sagas-8ie) : Redux + Sagas for efficient state management & and fine grain control on side effects processing such as async actions (ie fetching remote data from the API). Provides better separation of concern, enhances the system predictability, promotes code maintainability and performance through immutability patterns, one-way data flows by dispatching actions handled centrally, and by memoization of state selectors.  Also greatly contributes to infinite scaling of features.

- **Functional programming & react hooks**:  components are for the great majority pure functions. Side effects are handled using hooks. Both make for a more predictable system.  Allows to take full advantage of what ES6 and higher JavaScript has to offer : currying, generator functions, passing functions as props, composability, encapsulation, code reusability. Provides better separation of concerns and enhances code maintainability and performance through higher order & first order functions, lazy instantiation, chaining, piping and filtering.

- **Fine-grain exception handling** : Any exception thrown during runtime, including API calls exceptions, are handled gracefully and in a user-friendly fashion.

- **Spotify Login** + integration of **Web API** & **PlaybackState SDK** (in Beta as I write this on 20/11/2020)

## What I would do differently

- use Redux Toolkit
- plan better ahead of time for stable specs because once Redux is in the project, it can grow, but it is a very tedious process to modify any existing code because of all the boilerplate (unless redux toolkit is used ;)
- implement the [Private Route pattern](https://reactrouter.com/web/example/auth-workflow) using the react-router-dom
- Feature-centered directory structure 👍, like it is right now, but for greater coder’s convenience, I would include the redux-related files into the corresponding feature directory.  Right now, they do sit in their own feature directory, but are all sitting inside a `redux` directory, at root level. 
- Test-Driven Development is something I keep on putting to the side, although I periodically dive into the subject, for one day I will adopt the technique, I swear ;)

## App Features

- Spotify Remote Control: ability to control what Spotify is playing from this app, when any of the user's devices is actually active, by playing music, controlling volume, play/pause, skip back and forth, repeat & shuffle, adding tracks to the playing queue
- Display the playing track information on the remote control
- Search the Spotify database for Artists, Albums and Playlists
- Like/Unlike Playlists, Albums and tracks
- Display the user's top, recent, and liked tracks in the home page
- Add tracks to a playlist
- CRUD operations on playlists detailed information, and on track contents & track display order
- Get a radio based on a tracke
- Save the radio tracks to a playlist
- Copy the link of a track to share it
- Display the contents (info and tracks) of any playlist or albums available on Spotify
- Night Mode compliant

**Comment by boostup** [comment]
## App Features

- Spotify Remote Control: ability to control what Spotify is playing from this app, when any of the user's devices is actually active, by playing music, controlling volume, play/pause, skip back and forth, repeat & shuffle, adding tracks to the playing queue
- Display the playing track information on the remote control
- Search the Spotify database for Artists, Albums and Playlists
- Like/Unlike Playlists, Albums and tracks
- Display the user's top, recent, and liked tracks in the home page
- Add tracks to a playlist
- CRUD operations on playlists detailed information, and on track contents & track display order
- Get a radio based on a tracke
- Save the radio tracks to a playlist
- Copy the link of a track to share it
- Display the contents (info and tracks) of any playlist or albums available on Spotify
- Night Mode compliant
